// RootLayout or _app.tsx
import './globals.css';
import './css/style.css';

import { Inter } from 'next/font/google';
import Header from '@/components/ui/header';
import Footer from '@/components/ui/footer'; // Import the Footer component
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider appearance={{ variables: { colorPrimary: '#FB4570' } }}>
      <html lang="en">
        <body
          className={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}
        >
          <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer /> {/* Add the Footer component here */}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
